// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Resp.proto

package com.netboy.netty.solr.proto;

public final class RespSolrProto {
  private RespSolrProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.Resp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     *response format (xml, json, solr_javabin, csv ...)
     * </pre>
     */
    boolean hasResponseFormat();
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     *response format (xml, json, solr_javabin, csv ...)
     * </pre>
     */
    int getResponseFormat();

    /**
     * <code>optional bytes response = 3;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional bytes response = 3;</code>
     */
    com.google.protobuf.ByteString getResponse();

    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    int getErrorCode();

    /**
     * <code>optional string errorStr = 5;</code>
     */
    boolean hasErrorStr();
    /**
     * <code>optional string errorStr = 5;</code>
     */
    java.lang.String getErrorStr();
    /**
     * <code>optional string errorStr = 5;</code>
     */
    com.google.protobuf.ByteString
        getErrorStrBytes();
  }
  /**
   * Protobuf type {@code netty.Resp}
   */
  public static final class Resp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netty.Resp)
      RespOrBuilder {
    // Use Resp.newBuilder() to construct.
    private Resp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Resp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Resp defaultInstance;
    public static Resp getDefaultInstance() {
      return defaultInstance;
    }

    public Resp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Resp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              responseFormat_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              response_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              errorCode_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              errorStr_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netboy.netty.solr.proto.RespSolrProto.internal_static_netty_Resp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netboy.netty.solr.proto.RespSolrProto.internal_static_netty_Resp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netboy.netty.solr.proto.RespSolrProto.Resp.class, com.netboy.netty.solr.proto.RespSolrProto.Resp.Builder.class);
    }

    public static com.google.protobuf.Parser<Resp> PARSER =
        new com.google.protobuf.AbstractParser<Resp>() {
      public Resp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Resp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Resp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESPONSEFORMAT_FIELD_NUMBER = 2;
    private int responseFormat_;
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     *response format (xml, json, solr_javabin, csv ...)
     * </pre>
     */
    public boolean hasResponseFormat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     *response format (xml, json, solr_javabin, csv ...)
     * </pre>
     */
    public int getResponseFormat() {
      return responseFormat_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString response_;
    /**
     * <code>optional bytes response = 3;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes response = 3;</code>
     */
    public com.google.protobuf.ByteString getResponse() {
      return response_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ERRORSTR_FIELD_NUMBER = 5;
    private java.lang.Object errorStr_;
    /**
     * <code>optional string errorStr = 5;</code>
     */
    public boolean hasErrorStr() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string errorStr = 5;</code>
     */
    public java.lang.String getErrorStr() {
      java.lang.Object ref = errorStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorStr = 5;</code>
     */
    public com.google.protobuf.ByteString
        getErrorStrBytes() {
      java.lang.Object ref = errorStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      responseFormat_ = 0;
      response_ = com.google.protobuf.ByteString.EMPTY;
      errorCode_ = 0;
      errorStr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, responseFormat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, response_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, errorCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getErrorStrBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseFormat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, response_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, errorCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getErrorStrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netboy.netty.solr.proto.RespSolrProto.Resp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.netboy.netty.solr.proto.RespSolrProto.Resp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.Resp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.Resp)
        com.netboy.netty.solr.proto.RespSolrProto.RespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netboy.netty.solr.proto.RespSolrProto.internal_static_netty_Resp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netboy.netty.solr.proto.RespSolrProto.internal_static_netty_Resp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netboy.netty.solr.proto.RespSolrProto.Resp.class, com.netboy.netty.solr.proto.RespSolrProto.Resp.Builder.class);
      }

      // Construct using com.netboy.netty.solr.proto.RespSolrProto.Resp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        responseFormat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        response_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        errorStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netboy.netty.solr.proto.RespSolrProto.internal_static_netty_Resp_descriptor;
      }

      public com.netboy.netty.solr.proto.RespSolrProto.Resp getDefaultInstanceForType() {
        return com.netboy.netty.solr.proto.RespSolrProto.Resp.getDefaultInstance();
      }

      public com.netboy.netty.solr.proto.RespSolrProto.Resp build() {
        com.netboy.netty.solr.proto.RespSolrProto.Resp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netboy.netty.solr.proto.RespSolrProto.Resp buildPartial() {
        com.netboy.netty.solr.proto.RespSolrProto.Resp result = new com.netboy.netty.solr.proto.RespSolrProto.Resp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseFormat_ = responseFormat_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.response_ = response_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errorStr_ = errorStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netboy.netty.solr.proto.RespSolrProto.Resp) {
          return mergeFrom((com.netboy.netty.solr.proto.RespSolrProto.Resp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netboy.netty.solr.proto.RespSolrProto.Resp other) {
        if (other == com.netboy.netty.solr.proto.RespSolrProto.Resp.getDefaultInstance()) return this;
        if (other.hasResponseFormat()) {
          setResponseFormat(other.getResponseFormat());
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorStr()) {
          bitField0_ |= 0x00000008;
          errorStr_ = other.errorStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netboy.netty.solr.proto.RespSolrProto.Resp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netboy.netty.solr.proto.RespSolrProto.Resp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int responseFormat_ ;
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       *response format (xml, json, solr_javabin, csv ...)
       * </pre>
       */
      public boolean hasResponseFormat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       *response format (xml, json, solr_javabin, csv ...)
       * </pre>
       */
      public int getResponseFormat() {
        return responseFormat_;
      }
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       *response format (xml, json, solr_javabin, csv ...)
       * </pre>
       */
      public Builder setResponseFormat(int value) {
        bitField0_ |= 0x00000001;
        responseFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       *response format (xml, json, solr_javabin, csv ...)
       * </pre>
       */
      public Builder clearResponseFormat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseFormat_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response = 3;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes response = 3;</code>
       */
      public com.google.protobuf.ByteString getResponse() {
        return response_;
      }
      /**
       * <code>optional bytes response = 3;</code>
       */
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response = 3;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000002);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000004;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorStr_ = "";
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public boolean hasErrorStr() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public java.lang.String getErrorStr() {
        java.lang.Object ref = errorStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorStr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public com.google.protobuf.ByteString
          getErrorStrBytes() {
        java.lang.Object ref = errorStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public Builder setErrorStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public Builder clearErrorStr() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorStr_ = getDefaultInstance().getErrorStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public Builder setErrorStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorStr_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.Resp)
    }

    static {
      defaultInstance = new Resp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netty.Resp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Resp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_Resp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nResp.proto\022\005netty\"U\n\004Resp\022\026\n\016responseF" +
      "ormat\030\002 \001(\005\022\020\n\010response\030\003 \001(\014\022\021\n\terrorCo" +
      "de\030\004 \001(\005\022\020\n\010errorStr\030\005 \001(\tB.\n\033com.netboy" +
      ".netty.solr.protoB\rRespSolrProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_Resp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_Resp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netty_Resp_descriptor,
        new java.lang.String[] { "ResponseFormat", "Response", "ErrorCode", "ErrorStr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
