// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solr.proto

package com.netboy.netty.solr.proto;

public final class SolrProtocol {
  private SolrProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SolrNettyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.SolrNettyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 rid = 1;</code>
     */
    boolean hasRid();
    /**
     * <code>required int32 rid = 1;</code>
     */
    int getRid();

    /**
     * <code>required bytes params = 2;</code>
     *
     * <pre>
     *for string, json format, like http params
     * </pre>
     */
    boolean hasParams();
    /**
     * <code>required bytes params = 2;</code>
     *
     * <pre>
     *for string, json format, like http params
     * </pre>
     */
    com.google.protobuf.ByteString getParams();

    /**
     * <code>optional int32 streamsFormat = 3;</code>
     *
     * <pre>
     *(xml, json, solr_javabin) fix by params rt (request type)
     * </pre>
     */
    boolean hasStreamsFormat();
    /**
     * <code>optional int32 streamsFormat = 3;</code>
     *
     * <pre>
     *(xml, json, solr_javabin) fix by params rt (request type)
     * </pre>
     */
    int getStreamsFormat();

    /**
     * <code>repeated bytes streams = 4;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getStreamsList();
    /**
     * <code>repeated bytes streams = 4;</code>
     */
    int getStreamsCount();
    /**
     * <code>repeated bytes streams = 4;</code>
     */
    com.google.protobuf.ByteString getStreams(int index);
  }
  /**
   * Protobuf type {@code netty.SolrNettyRequest}
   */
  public static final class SolrNettyRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netty.SolrNettyRequest)
      SolrNettyRequestOrBuilder {
    // Use SolrNettyRequest.newBuilder() to construct.
    private SolrNettyRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SolrNettyRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SolrNettyRequest defaultInstance;
    public static SolrNettyRequest getDefaultInstance() {
      return defaultInstance;
    }

    public SolrNettyRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SolrNettyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              params_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              streamsFormat_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                streams_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              streams_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          streams_ = java.util.Collections.unmodifiableList(streams_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest.class, com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<SolrNettyRequest> PARSER =
        new com.google.protobuf.AbstractParser<SolrNettyRequest>() {
      public SolrNettyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SolrNettyRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SolrNettyRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RID_FIELD_NUMBER = 1;
    private int rid_;
    /**
     * <code>required int32 rid = 1;</code>
     */
    public boolean hasRid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rid = 1;</code>
     */
    public int getRid() {
      return rid_;
    }

    public static final int PARAMS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString params_;
    /**
     * <code>required bytes params = 2;</code>
     *
     * <pre>
     *for string, json format, like http params
     * </pre>
     */
    public boolean hasParams() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes params = 2;</code>
     *
     * <pre>
     *for string, json format, like http params
     * </pre>
     */
    public com.google.protobuf.ByteString getParams() {
      return params_;
    }

    public static final int STREAMSFORMAT_FIELD_NUMBER = 3;
    private int streamsFormat_;
    /**
     * <code>optional int32 streamsFormat = 3;</code>
     *
     * <pre>
     *(xml, json, solr_javabin) fix by params rt (request type)
     * </pre>
     */
    public boolean hasStreamsFormat() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 streamsFormat = 3;</code>
     *
     * <pre>
     *(xml, json, solr_javabin) fix by params rt (request type)
     * </pre>
     */
    public int getStreamsFormat() {
      return streamsFormat_;
    }

    public static final int STREAMS_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> streams_;
    /**
     * <code>repeated bytes streams = 4;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getStreamsList() {
      return streams_;
    }
    /**
     * <code>repeated bytes streams = 4;</code>
     */
    public int getStreamsCount() {
      return streams_.size();
    }
    /**
     * <code>repeated bytes streams = 4;</code>
     */
    public com.google.protobuf.ByteString getStreams(int index) {
      return streams_.get(index);
    }

    private void initFields() {
      rid_ = 0;
      params_ = com.google.protobuf.ByteString.EMPTY;
      streamsFormat_ = 0;
      streams_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParams()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, params_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, streamsFormat_);
      }
      for (int i = 0; i < streams_.size(); i++) {
        output.writeBytes(4, streams_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, params_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, streamsFormat_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < streams_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(streams_.get(i));
        }
        size += dataSize;
        size += 1 * getStreamsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.SolrNettyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.SolrNettyRequest)
        com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest.class, com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest.Builder.class);
      }

      // Construct using com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        params_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        streamsFormat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        streams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyRequest_descriptor;
      }

      public com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest getDefaultInstanceForType() {
        return com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest.getDefaultInstance();
      }

      public com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest build() {
        com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest buildPartial() {
        com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest result = new com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rid_ = rid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.params_ = params_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.streamsFormat_ = streamsFormat_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          streams_ = java.util.Collections.unmodifiableList(streams_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.streams_ = streams_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest) {
          return mergeFrom((com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest other) {
        if (other == com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest.getDefaultInstance()) return this;
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        if (other.hasParams()) {
          setParams(other.getParams());
        }
        if (other.hasStreamsFormat()) {
          setStreamsFormat(other.getStreamsFormat());
        }
        if (!other.streams_.isEmpty()) {
          if (streams_.isEmpty()) {
            streams_ = other.streams_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureStreamsIsMutable();
            streams_.addAll(other.streams_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRid()) {
          
          return false;
        }
        if (!hasParams()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netboy.netty.solr.proto.SolrProtocol.SolrNettyRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rid_ ;
      /**
       * <code>required int32 rid = 1;</code>
       */
      public boolean hasRid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rid = 1;</code>
       */
      public int getRid() {
        return rid_;
      }
      /**
       * <code>required int32 rid = 1;</code>
       */
      public Builder setRid(int value) {
        bitField0_ |= 0x00000001;
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rid = 1;</code>
       */
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rid_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString params_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes params = 2;</code>
       *
       * <pre>
       *for string, json format, like http params
       * </pre>
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes params = 2;</code>
       *
       * <pre>
       *for string, json format, like http params
       * </pre>
       */
      public com.google.protobuf.ByteString getParams() {
        return params_;
      }
      /**
       * <code>required bytes params = 2;</code>
       *
       * <pre>
       *for string, json format, like http params
       * </pre>
       */
      public Builder setParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        params_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes params = 2;</code>
       *
       * <pre>
       *for string, json format, like http params
       * </pre>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000002);
        params_ = getDefaultInstance().getParams();
        onChanged();
        return this;
      }

      private int streamsFormat_ ;
      /**
       * <code>optional int32 streamsFormat = 3;</code>
       *
       * <pre>
       *(xml, json, solr_javabin) fix by params rt (request type)
       * </pre>
       */
      public boolean hasStreamsFormat() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 streamsFormat = 3;</code>
       *
       * <pre>
       *(xml, json, solr_javabin) fix by params rt (request type)
       * </pre>
       */
      public int getStreamsFormat() {
        return streamsFormat_;
      }
      /**
       * <code>optional int32 streamsFormat = 3;</code>
       *
       * <pre>
       *(xml, json, solr_javabin) fix by params rt (request type)
       * </pre>
       */
      public Builder setStreamsFormat(int value) {
        bitField0_ |= 0x00000004;
        streamsFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 streamsFormat = 3;</code>
       *
       * <pre>
       *(xml, json, solr_javabin) fix by params rt (request type)
       * </pre>
       */
      public Builder clearStreamsFormat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        streamsFormat_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> streams_ = java.util.Collections.emptyList();
      private void ensureStreamsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          streams_ = new java.util.ArrayList<com.google.protobuf.ByteString>(streams_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bytes streams = 4;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getStreamsList() {
        return java.util.Collections.unmodifiableList(streams_);
      }
      /**
       * <code>repeated bytes streams = 4;</code>
       */
      public int getStreamsCount() {
        return streams_.size();
      }
      /**
       * <code>repeated bytes streams = 4;</code>
       */
      public com.google.protobuf.ByteString getStreams(int index) {
        return streams_.get(index);
      }
      /**
       * <code>repeated bytes streams = 4;</code>
       */
      public Builder setStreams(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStreamsIsMutable();
        streams_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes streams = 4;</code>
       */
      public Builder addStreams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStreamsIsMutable();
        streams_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes streams = 4;</code>
       */
      public Builder addAllStreams(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureStreamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, streams_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes streams = 4;</code>
       */
      public Builder clearStreams() {
        streams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.SolrNettyRequest)
    }

    static {
      defaultInstance = new SolrNettyRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netty.SolrNettyRequest)
  }

  public interface SolrNettyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.SolrNettyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 rid = 1;</code>
     */
    boolean hasRid();
    /**
     * <code>required int32 rid = 1;</code>
     */
    int getRid();

    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     *response format (xml, json, solr_javabin, csv ...)
     * </pre>
     */
    boolean hasResponseFormat();
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     *response format (xml, json, solr_javabin, csv ...)
     * </pre>
     */
    int getResponseFormat();

    /**
     * <code>optional bytes response = 3;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional bytes response = 3;</code>
     */
    com.google.protobuf.ByteString getResponse();

    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    int getErrorCode();

    /**
     * <code>optional string errorStr = 5;</code>
     */
    boolean hasErrorStr();
    /**
     * <code>optional string errorStr = 5;</code>
     */
    java.lang.String getErrorStr();
    /**
     * <code>optional string errorStr = 5;</code>
     */
    com.google.protobuf.ByteString
        getErrorStrBytes();
  }
  /**
   * Protobuf type {@code netty.SolrNettyResponse}
   */
  public static final class SolrNettyResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netty.SolrNettyResponse)
      SolrNettyResponseOrBuilder {
    // Use SolrNettyResponse.newBuilder() to construct.
    private SolrNettyResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SolrNettyResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SolrNettyResponse defaultInstance;
    public static SolrNettyResponse getDefaultInstance() {
      return defaultInstance;
    }

    public SolrNettyResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SolrNettyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              responseFormat_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              response_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              errorCode_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              errorStr_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse.class, com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<SolrNettyResponse> PARSER =
        new com.google.protobuf.AbstractParser<SolrNettyResponse>() {
      public SolrNettyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SolrNettyResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SolrNettyResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RID_FIELD_NUMBER = 1;
    private int rid_;
    /**
     * <code>required int32 rid = 1;</code>
     */
    public boolean hasRid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rid = 1;</code>
     */
    public int getRid() {
      return rid_;
    }

    public static final int RESPONSEFORMAT_FIELD_NUMBER = 2;
    private int responseFormat_;
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     *response format (xml, json, solr_javabin, csv ...)
     * </pre>
     */
    public boolean hasResponseFormat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 responseFormat = 2;</code>
     *
     * <pre>
     *response format (xml, json, solr_javabin, csv ...)
     * </pre>
     */
    public int getResponseFormat() {
      return responseFormat_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString response_;
    /**
     * <code>optional bytes response = 3;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes response = 3;</code>
     */
    public com.google.protobuf.ByteString getResponse() {
      return response_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 errorCode = 4;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ERRORSTR_FIELD_NUMBER = 5;
    private java.lang.Object errorStr_;
    /**
     * <code>optional string errorStr = 5;</code>
     */
    public boolean hasErrorStr() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string errorStr = 5;</code>
     */
    public java.lang.String getErrorStr() {
      java.lang.Object ref = errorStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorStr = 5;</code>
     */
    public com.google.protobuf.ByteString
        getErrorStrBytes() {
      java.lang.Object ref = errorStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rid_ = 0;
      responseFormat_ = 0;
      response_ = com.google.protobuf.ByteString.EMPTY;
      errorCode_ = 0;
      errorStr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, responseFormat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, response_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, errorCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getErrorStrBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseFormat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, response_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, errorCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getErrorStrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.SolrNettyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.SolrNettyResponse)
        com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse.class, com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse.Builder.class);
      }

      // Construct using com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseFormat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        response_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        errorStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netboy.netty.solr.proto.SolrProtocol.internal_static_netty_SolrNettyResponse_descriptor;
      }

      public com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse getDefaultInstanceForType() {
        return com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse.getDefaultInstance();
      }

      public com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse build() {
        com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse buildPartial() {
        com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse result = new com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rid_ = rid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseFormat_ = responseFormat_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.response_ = response_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.errorStr_ = errorStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse) {
          return mergeFrom((com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse other) {
        if (other == com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse.getDefaultInstance()) return this;
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        if (other.hasResponseFormat()) {
          setResponseFormat(other.getResponseFormat());
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorStr()) {
          bitField0_ |= 0x00000010;
          errorStr_ = other.errorStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netboy.netty.solr.proto.SolrProtocol.SolrNettyResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rid_ ;
      /**
       * <code>required int32 rid = 1;</code>
       */
      public boolean hasRid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rid = 1;</code>
       */
      public int getRid() {
        return rid_;
      }
      /**
       * <code>required int32 rid = 1;</code>
       */
      public Builder setRid(int value) {
        bitField0_ |= 0x00000001;
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rid = 1;</code>
       */
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rid_ = 0;
        onChanged();
        return this;
      }

      private int responseFormat_ ;
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       *response format (xml, json, solr_javabin, csv ...)
       * </pre>
       */
      public boolean hasResponseFormat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       *response format (xml, json, solr_javabin, csv ...)
       * </pre>
       */
      public int getResponseFormat() {
        return responseFormat_;
      }
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       *response format (xml, json, solr_javabin, csv ...)
       * </pre>
       */
      public Builder setResponseFormat(int value) {
        bitField0_ |= 0x00000002;
        responseFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 responseFormat = 2;</code>
       *
       * <pre>
       *response format (xml, json, solr_javabin, csv ...)
       * </pre>
       */
      public Builder clearResponseFormat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseFormat_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response = 3;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes response = 3;</code>
       */
      public com.google.protobuf.ByteString getResponse() {
        return response_;
      }
      /**
       * <code>optional bytes response = 3;</code>
       */
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response = 3;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000004);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000008;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 4;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorStr_ = "";
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public boolean hasErrorStr() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public java.lang.String getErrorStr() {
        java.lang.Object ref = errorStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorStr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public com.google.protobuf.ByteString
          getErrorStrBytes() {
        java.lang.Object ref = errorStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public Builder setErrorStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errorStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public Builder clearErrorStr() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errorStr_ = getDefaultInstance().getErrorStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorStr = 5;</code>
       */
      public Builder setErrorStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errorStr_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.SolrNettyResponse)
    }

    static {
      defaultInstance = new SolrNettyResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netty.SolrNettyResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_SolrNettyRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_SolrNettyRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_SolrNettyResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_SolrNettyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nsolr.proto\022\005netty\"W\n\020SolrNettyRequest\022" +
      "\013\n\003rid\030\001 \002(\005\022\016\n\006params\030\002 \002(\014\022\025\n\rstreamsF" +
      "ormat\030\003 \001(\005\022\017\n\007streams\030\004 \003(\014\"o\n\021SolrNett" +
      "yResponse\022\013\n\003rid\030\001 \002(\005\022\026\n\016responseFormat" +
      "\030\002 \001(\005\022\020\n\010response\030\003 \001(\014\022\021\n\terrorCode\030\004 " +
      "\001(\005\022\020\n\010errorStr\030\005 \001(\tB-\n\033com.netboy.nett" +
      "y.solr.protoB\014SolrProtocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_SolrNettyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_SolrNettyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netty_SolrNettyRequest_descriptor,
        new java.lang.String[] { "Rid", "Params", "StreamsFormat", "Streams", });
    internal_static_netty_SolrNettyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_netty_SolrNettyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netty_SolrNettyResponse_descriptor,
        new java.lang.String[] { "Rid", "ResponseFormat", "Response", "ErrorCode", "ErrorStr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
